kotlin.code.style=official

#maven central
mavenCentralPublishing=true
signAllPublications=true

#checksum files
mavenCentralChecksums=md5,sha1,sha256,sha512
mavenCentralExcludeSignatureChecksums=false

#The POM
GROUP=de.fridolin1
POM_ARTIFACT_ID=lecs4k
VERSION_NAME=0.6-SNAPSHOT

POM_NAME=lecs4k
POM_DESCRIPTION=Lightweight Entity Component System 4 Kotlin (and Java)
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/Fridolin42/lecs4k

POM_LICENSE_NAME=LGPL-3.0 license
POM_LICENSE_URL=https://www.gnu.org/licenses/lgpl-3.0.en.html
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/Fridolin42/lecs4k
POM_SCM_CONNECTION=scm:git:git://github.com/Fridolin42/lecs4k.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Fridolin42/lecs4k.git

POM_DEVELOPER_ID=fridolin1
POM_DEVELOPER_NAME=Fridolin
POM_DEVELOPER_URL=https://github.com/Fridolin42/
